name: deploy
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - uses: actions/checkout@v2
      - name: Make env file
        uses: SpicyPizza/create-envfile@v1.2
        with:
          envkey_DEBUG: false
          envkey_MICRO_CMS_SERVICE_KEY: ${{secrets.MICRO_CMS_SERVICE_KEY}}
          envkey_MICRO_CMS_API_KEY: ${{secrets.MICRO_CMS_API_KEY}}
          envkey_NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: ${{secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID}}
          envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          file_name: .env
      - uses: amondnet/vercel-action@v20
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Optional
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-args: '--prod' # Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required